
apiVersion: v1
kind: ConfigMap
metadata:
  name: srs-config
data:
  srs.conf: |-
    listen              1935;
    max_connections     1000;
    srs_log_tank        console;
    daemon              off;
    http_api {
        enabled         on;
        listen          1985;
    }
    http_server {
        enabled         on;
        listen          8080;
        dir             ./objs/nginx/html;
    }

    stats {
        network         0;
        disk            sda sdb xvda xvdb;
    }

    rtc_server {
        enabled         on;
        # Listen at udp://8000
        listen          8000;
        #
        # The $CANDIDATE means fetch from env, if not configed, use * as default.
        #
        # The * means retrieving server IP automatically, from all network interfaces,
        # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
        candidate       $CANDIDATE;
    }

    vhost __defaultVhost__ {
        http_remux {
            enabled     on;
            mount       [vhost]/[app]/[stream].flv;
        }
        hls {
            enabled         on;
            # hls_dispose     30;
        }
        rtc {
           enabled     on;
           bframe      discard;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-deployment
  labels:
    app: srs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs
  template:
    metadata:
      labels:
        app: srs
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: srs-config
      containers:
      - name: srs
        image: ossrs/srs:3
        ports:
        - containerPort: 1935
        - containerPort: 1985
        - containerPort: 8080
        - containerPort: 8000
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/srs/conf
        env:
        - name: CANDIDATE
          value: 112.74.49.196
---

apiVersion: v1
kind: Service
metadata:
  name: srs-service
spec:
  type: LoadBalancer
  selector:
    app: srs
  ports:
  - name: srs-service-1935-1935
    port: 1935
    protocol: TCP
    targetPort: 1935
  - name: srs-service-1985-1985
    port: 1985
    protocol: TCP
    targetPort: 1985
  - name: srs-service-8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: srs-service-8000-8000
    port: 8000
    #protocol: TCP
    targetPort: 8000
